"""RoboCasa kitchen scene builder for MuJoCo frame server.

Loads an exported RoboCasa kitchen scene (robot-stripped XML) and attaches
the G1 humanoid robot with stereo cameras and actuators.

The scene XML is pre-generated by export_robocasa_scene.py + strip_robocasa_robot.py.
"""
from __future__ import annotations

from pathlib import Path

import mujoco
import numpy as np
from mjlab.actuator.actuator import TransmissionType
from mjlab.utils.spec import create_position_actuator
from parkour_onnx_policy import G1_JOINT_ORDER

from robot_config import (
    CAMERA_OFFSET_POS,
    CAMERA_OFFSET_QUAT_WXYZ,
    JOINT_ARMATURE,
    JOINT_KD,
    JOINT_KP,
    JOINT_TORQUE_LIMIT,
    TORSO_BODY_NAME,
)

# ── Physics ───────────────────────────────────────────────────────────────
SIM_DT = 0.005
CONTROL_DT = 0.02

# ── Stereo camera ─────────────────────────────────────────────────────────
_STEREO_MOUNT_POS = (0.15, 0.0, 0.3)
_STEREO_HALF_BASELINE = 0.060057
_STEREO_FOVY = 46.8
_STEREO_RES = (1280, 720)
_STEREO_QUAT_WXYZ = (0.454519, 0.454519, -0.541675, -0.541675)

# ── Scene file ────────────────────────────────────────────────────────────
_SCENE_XML = Path(__file__).parent / "robocasa_kitchen_scene.xml"


def _add_depth_camera(spec: mujoco.MjSpec) -> None:
    torso_body = spec.body(TORSO_BODY_NAME)
    cam = torso_body.add_camera()
    cam.name = "head_depth"
    cam.pos[:] = CAMERA_OFFSET_POS
    cam.quat[:] = CAMERA_OFFSET_QUAT_WXYZ
    cam.fovy = 58.29


def _add_stereo_cameras(spec: mujoco.MjSpec) -> None:
    torso = spec.body(TORSO_BODY_NAME)
    mount = torso.add_body()
    mount.name = "stereo_camera_mount"
    mount.pos[:] = _STEREO_MOUNT_POS
    mount.mass = 0.1
    mount.inertia[:] = (0.0001, 0.0001, 0.0001)

    # Yaw joint (rotate left/right around local z-axis)
    yaw_joint = mount.add_joint()
    yaw_joint.name = "stereo_cam_yaw"
    yaw_joint.type = mujoco.mjtJoint.mjJNT_HINGE
    yaw_joint.axis[:] = (0, 0, 1)
    yaw_joint.range[:] = (-1.0, 1.0)
    yaw_joint.limited = True

    # Tilt body for pitch
    tilt = mount.add_body()
    tilt.name = "stereo_cam_tilt"
    tilt.mass = 0.1
    tilt.inertia[:] = (0.0001, 0.0001, 0.0001)

    # Pitch joint (rotate up/down around local y-axis)
    pitch_joint = tilt.add_joint()
    pitch_joint.name = "stereo_cam_pitch"
    pitch_joint.type = mujoco.mjtJoint.mjJNT_HINGE
    pitch_joint.axis[:] = (0, 1, 0)
    pitch_joint.range[:] = (-0.8, 0.8)
    pitch_joint.limited = True

    left = tilt.add_camera()
    left.name = "cam_left"
    left.pos[:] = (0.0, _STEREO_HALF_BASELINE, 0.0)
    left.quat[:] = _STEREO_QUAT_WXYZ
    left.fovy = _STEREO_FOVY
    left.resolution[:] = _STEREO_RES

    right = tilt.add_camera()
    right.name = "cam_right"
    right.pos[:] = (0.0, -_STEREO_HALF_BASELINE, 0.0)
    right.quat[:] = _STEREO_QUAT_WXYZ
    right.fovy = _STEREO_FOVY
    right.resolution[:] = _STEREO_RES


def _add_solver(spec: mujoco.MjSpec) -> None:
    spec.option.timestep = SIM_DT
    spec.option.integrator = mujoco.mjtIntegrator.mjINT_IMPLICITFAST
    spec.option.iterations = 10
    spec.option.ls_iterations = 20
    spec.option.noslip_iterations = 0
    spec.option.ccd_iterations = 128
    spec.nconmax = max(spec.nconmax, 5000)
    spec.njmax = max(spec.njmax, 5000)


def _add_actuators(spec: mujoco.MjSpec) -> None:
    for idx, joint_name in enumerate(G1_JOINT_ORDER):
        create_position_actuator(
            spec,
            joint_name,
            stiffness=float(JOINT_KP[idx]),
            damping=float(JOINT_KD[idx]),
            effort_limit=float(JOINT_TORQUE_LIMIT[idx]),
            armature=float(JOINT_ARMATURE[idx]),
            transmission_type=TransmissionType.JOINT,
        )


def build_robocasa_scene_preview() -> mujoco.MjModel:
    """Build the RoboCasa kitchen scene WITHOUT the robot (for placement preview)."""
    scene_spec = mujoco.MjSpec.from_file(str(_SCENE_XML))
    _add_solver(scene_spec)
    scene_spec.visual.map.znear = 0.001
    return scene_spec.compile()


def build_robocasa_scene(
    robot_xml_path: Path,
    spawn_pos: tuple[float, float, float] = (2.3, -2.7, 0.0),
) -> mujoco.MjModel:
    """Build a RoboCasa kitchen scene with the G1 robot at *spawn_pos*."""
    scene_spec = mujoco.MjSpec.from_file(str(_SCENE_XML))

    # Load robot spec
    robot_spec = mujoco.MjSpec.from_file(str(robot_xml_path))

    # Create attachment frame at the user-specified position
    robot_frame = scene_spec.worldbody.add_frame()
    robot_frame.name = "robot_attach"
    robot_frame.pos[:] = spawn_pos

    # Attach robot to scene
    scene_spec.attach(robot_spec, frame=robot_frame, prefix="")

    # Configure solver (override RoboCasa's settings for our robot)
    _add_solver(scene_spec)

    # Add cameras to robot torso
    _add_depth_camera(scene_spec)
    _add_stereo_cameras(scene_spec)

    # Add actuators for G1 joints
    _add_actuators(scene_spec)

    # Offscreen framebuffer
    scene_spec.visual.global_.offwidth = max(scene_spec.visual.global_.offwidth, _STEREO_RES[0])
    scene_spec.visual.global_.offheight = max(scene_spec.visual.global_.offheight, _STEREO_RES[1])
    scene_spec.visual.map.znear = 0.001

    return scene_spec.compile()
